### ISSUE TITLE
过滤

### ISSUE THREAD

**Issue by SiMaLaoShi** [Xu-Angel/Girl#1]
过滤数字信息可以为区间，城市信息希望精确到某个市，就是过滤信息是区间upup

**Comment by SiMaLaoShi** [comment]
查看详情后没有过滤

**Comment by Xu-Angel** [comment]
> 过滤数字信息可以为区间，城市信息希望精确到某个市，就是过滤信息是区间upup

这个后期做，前期先做好大功能先。欢迎PR 代码，提出你的想法~
