### ISSUE TITLE
登录不了啊

### ISSUE THREAD

**Issue by wanglang1995** [Xu-Angel/Girl#5]
咋回事啊

**Comment by wanglang1995** [comment]
Error in MongoDb connection: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by Xu-Angel** [comment]
> Error in MongoDb connection: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

是线上 还是你本地运行？这种错误出现几率比较少，数据库连接错误，属于偶发性，再登一次就行~

**Comment by Xu-Angel** [comment]
> Error in MongoDb connection: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

数据库没打开，第一次连接失败。打开数据库 再跑一次就行~

**Comment by wanglang1995** [comment]
> > MongoDb连接出错：MongoNetworkError：第一次连接时无法连接到服务器[127.0.0.1:27017] [MongoNetworkError：connect ECONNREFUSED 127.0.0.1:27017]
> 
> 数据库没打开，第一次连接失败。打开数据库再跑一次就行〜

我数据库开不了啊,是MySQL吗?我用的Navicat
